### ISSUE TITLE
Fazer a pesquisa

### ISSUE THREAD

**Issue by PomboN9878** [PomboN9878/ProjetoWebIntelInfo#1]

**Comment by AlanPan07** [comment]
[Pesquisa IntelInfo.docx](https://github.com/PomboN9878/ProjetoWebIntelInfo/files/12664287/Pesquisa.IntelInfo.docx)

**Comment by AlanPan07** [comment]
https://www.hardware.com.br/artigos/12-curiosidades-sobre-a-intel/
